language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
#  - rbx-18mode # rbx 1.8 dies on #define_singleton_method for some reason.
#  - jruby # jruby dies because of sqlite3 dependency
  - rbx-19mode
  - ree
branches:
  only:
    - master
